# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_equipment_controler.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 700))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 700))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color:#1f1d2c;\n"
"font: 75 9pt \"Trebuchet MS\";")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(-4, -1, 1031, 771))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"}\n"
"QTabBar::tab {\n"
"    padding: 15px;\n"
"    padding-top: 9px;\n"
"    padding-bottom: 9px;\n"
"    background: #262837;\n"
"    color: rgb(239, 239, 239);\n"
"border-top-right-radius: 10px 10px;\n"
"border-top-left-radius: 10px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #2e303f;\n"
"    background-color: #2e303f;\n"
"    color: rgb(239, 239, 239);\n"
"}\n"
"QTabBar::tab:hover {\n"
"    background: #181722;\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_starting_page = QtWidgets.QWidget()
        self.tab_starting_page.setStyleSheet("background-color: #2e303f;")
        self.tab_starting_page.setObjectName("tab_starting_page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_starting_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 991, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 75 15pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_starting_page, "")
        self.tab_RigolDp832 = QtWidgets.QWidget()
        self.tab_RigolDp832.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_RigolDp832.setAutoFillBackground(False)
        self.tab_RigolDp832.setStyleSheet("background-color: #2e303f;")
        self.tab_RigolDp832.setObjectName("tab_RigolDp832")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_RigolDp832)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 0, 951, 280))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_channel_1 = QtWidgets.QGridLayout()
        self.gridLayout_channel_1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_channel_1.setObjectName("gridLayout_channel_1")
        self.pushButton_ovp_channel_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ovp_channel_1.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_ovp_channel_1.setFont(font)
        self.pushButton_ovp_channel_1.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.pushButton_ovp_channel_1.setObjectName("pushButton_ovp_channel_1")
        self.gridLayout_channel_1.addWidget(self.pushButton_ovp_channel_1, 4, 2, 1, 1)
        self.label_channel_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_channel_1.setFont(font)
        self.label_channel_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_channel_1.setStyleSheet("font: 75 14pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_channel_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_1.setObjectName("label_channel_1")
        self.gridLayout_channel_1.addWidget(self.label_channel_1, 1, 1, 1, 2)
        self.pushButton_enable_channel_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_enable_channel_1.sizePolicy().hasHeightForWidth())
        self.pushButton_enable_channel_1.setSizePolicy(sizePolicy)
        self.pushButton_enable_channel_1.setMinimumSize(QtCore.QSize(130, 45))
        self.pushButton_enable_channel_1.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_enable_channel_1.setFont(font)
        self.pushButton_enable_channel_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_enable_channel_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_enable_channel_1.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font: 75 11pt \"Trebuchet MS\";")
        self.pushButton_enable_channel_1.setObjectName("pushButton_enable_channel_1")
        self.gridLayout_channel_1.addWidget(self.pushButton_enable_channel_1, 6, 1, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_ovp_channel_1 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_ovp_channel_1.setFont(font)
        self.doubleSpinBox_ovp_channel_1.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_ovp_channel_1.setDecimals(3)
        self.doubleSpinBox_ovp_channel_1.setMaximum(30.0)
        self.doubleSpinBox_ovp_channel_1.setSingleStep(1.0)
        self.doubleSpinBox_ovp_channel_1.setObjectName("doubleSpinBox_ovp_channel_1")
        self.gridLayout_channel_1.addWidget(self.doubleSpinBox_ovp_channel_1, 4, 1, 1, 1)
        self.pushButton_ocp_channel_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ocp_channel_1.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_ocp_channel_1.setFont(font)
        self.pushButton_ocp_channel_1.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.pushButton_ocp_channel_1.setObjectName("pushButton_ocp_channel_1")
        self.gridLayout_channel_1.addWidget(self.pushButton_ocp_channel_1, 5, 2, 1, 1)
        self.label_current_channel_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_current_channel_1.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_current_channel_1.setObjectName("label_current_channel_1")
        self.gridLayout_channel_1.addWidget(self.label_current_channel_1, 3, 0, 1, 1)
        self.label_voltage_channel_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_voltage_channel_1.setFont(font)
        self.label_voltage_channel_1.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_voltage_channel_1.setObjectName("label_voltage_channel_1")
        self.gridLayout_channel_1.addWidget(self.label_voltage_channel_1, 2, 0, 1, 1)
        self.label_ocp_channel_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ocp_channel_1.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_ocp_channel_1.setObjectName("label_ocp_channel_1")
        self.gridLayout_channel_1.addWidget(self.label_ocp_channel_1, 5, 0, 1, 1)
        self.label_ovp_channel_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ovp_channel_1.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_ovp_channel_1.setObjectName("label_ovp_channel_1")
        self.gridLayout_channel_1.addWidget(self.label_ovp_channel_1, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_channel_1.addItem(spacerItem1, 2, 3, 1, 1)
        self.doubleSpinBox_ocp_channel_1 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_ocp_channel_1.setFont(font)
        self.doubleSpinBox_ocp_channel_1.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_ocp_channel_1.setDecimals(3)
        self.doubleSpinBox_ocp_channel_1.setMaximum(3.0)
        self.doubleSpinBox_ocp_channel_1.setSingleStep(0.1)
        self.doubleSpinBox_ocp_channel_1.setObjectName("doubleSpinBox_ocp_channel_1")
        self.gridLayout_channel_1.addWidget(self.doubleSpinBox_ocp_channel_1, 5, 1, 1, 1)
        self.doubleSpinBox_voltage_channel_1 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_voltage_channel_1.setFont(font)
        self.doubleSpinBox_voltage_channel_1.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_voltage_channel_1.setDecimals(3)
        self.doubleSpinBox_voltage_channel_1.setMaximum(30.0)
        self.doubleSpinBox_voltage_channel_1.setSingleStep(1.0)
        self.doubleSpinBox_voltage_channel_1.setObjectName("doubleSpinBox_voltage_channel_1")
        self.gridLayout_channel_1.addWidget(self.doubleSpinBox_voltage_channel_1, 2, 1, 1, 2)
        self.doubleSpinBox_current_channel_1 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_current_channel_1.setFont(font)
        self.doubleSpinBox_current_channel_1.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_current_channel_1.setDecimals(3)
        self.doubleSpinBox_current_channel_1.setMaximum(3.0)
        self.doubleSpinBox_current_channel_1.setSingleStep(0.1)
        self.doubleSpinBox_current_channel_1.setObjectName("doubleSpinBox_current_channel_1")
        self.gridLayout_channel_1.addWidget(self.doubleSpinBox_current_channel_1, 3, 1, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_voltage_measured_values_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_voltage_measured_values_1.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_voltage_measured_values_1.setObjectName("pushButton_voltage_measured_values_1")
        self.horizontalLayout_2.addWidget(self.pushButton_voltage_measured_values_1)
        self.pushButton_current_measured_values_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_current_measured_values_1.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_current_measured_values_1.setObjectName("pushButton_current_measured_values_1")
        self.horizontalLayout_2.addWidget(self.pushButton_current_measured_values_1)
        self.pushButton_power_measured_values_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_power_measured_values_1.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_power_measured_values_1.setObjectName("pushButton_power_measured_values_1")
        self.horizontalLayout_2.addWidget(self.pushButton_power_measured_values_1)
        self.gridLayout_channel_1.addLayout(self.horizontalLayout_2, 7, 0, 1, 4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_cvcc_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_cvcc_1.setMinimumSize(QtCore.QSize(30, 0))
        self.label_cvcc_1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_cvcc_1.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_cvcc_1.setObjectName("label_cvcc_1")
        self.horizontalLayout_5.addWidget(self.label_cvcc_1)
        self.led_cvcc_1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_cvcc_1.sizePolicy().hasHeightForWidth())
        self.led_cvcc_1.setSizePolicy(sizePolicy)
        self.led_cvcc_1.setMinimumSize(QtCore.QSize(25, 25))
        self.led_cvcc_1.setMaximumSize(QtCore.QSize(25, 25))
        self.led_cvcc_1.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(0, 255, 127)")
        self.led_cvcc_1.setText("")
        self.led_cvcc_1.setPixmap(QtGui.QPixmap("../../../Desktop/leb_disabled - Copy.png"))
        self.led_cvcc_1.setScaledContents(True)
        self.led_cvcc_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.led_cvcc_1.setObjectName("led_cvcc_1")
        self.horizontalLayout_5.addWidget(self.led_cvcc_1)
        self.gridLayout_channel_1.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_channel_1)
        self.line_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.gridLayout_channel_2 = QtWidgets.QGridLayout()
        self.gridLayout_channel_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_channel_2.setObjectName("gridLayout_channel_2")
        self.label_voltage_channel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_voltage_channel_2.setFont(font)
        self.label_voltage_channel_2.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_voltage_channel_2.setObjectName("label_voltage_channel_2")
        self.gridLayout_channel_2.addWidget(self.label_voltage_channel_2, 2, 0, 1, 1)
        self.pushButton_ovp_channel_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ovp_channel_2.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_ovp_channel_2.setFont(font)
        self.pushButton_ovp_channel_2.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.pushButton_ovp_channel_2.setObjectName("pushButton_ovp_channel_2")
        self.gridLayout_channel_2.addWidget(self.pushButton_ovp_channel_2, 4, 2, 1, 1)
        self.pushButton_enable_channel_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_enable_channel_2.sizePolicy().hasHeightForWidth())
        self.pushButton_enable_channel_2.setSizePolicy(sizePolicy)
        self.pushButton_enable_channel_2.setMinimumSize(QtCore.QSize(130, 45))
        self.pushButton_enable_channel_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_enable_channel_2.setFont(font)
        self.pushButton_enable_channel_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_enable_channel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_enable_channel_2.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font: 75 11pt \"Trebuchet MS\";")
        self.pushButton_enable_channel_2.setObjectName("pushButton_enable_channel_2")
        self.gridLayout_channel_2.addWidget(self.pushButton_enable_channel_2, 6, 1, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_channel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_channel_2.setFont(font)
        self.label_channel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_channel_2.setStyleSheet("font: 75 14pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_channel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_2.setObjectName("label_channel_2")
        self.gridLayout_channel_2.addWidget(self.label_channel_2, 1, 1, 1, 2)
        self.pushButton_ocp_channel_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ocp_channel_2.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_ocp_channel_2.setFont(font)
        self.pushButton_ocp_channel_2.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.pushButton_ocp_channel_2.setObjectName("pushButton_ocp_channel_2")
        self.gridLayout_channel_2.addWidget(self.pushButton_ocp_channel_2, 5, 2, 1, 1)
        self.label_current_channel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_current_channel_2.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_current_channel_2.setObjectName("label_current_channel_2")
        self.gridLayout_channel_2.addWidget(self.label_current_channel_2, 3, 0, 1, 1)
        self.doubleSpinBox_ovp_channel_2 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_ovp_channel_2.setFont(font)
        self.doubleSpinBox_ovp_channel_2.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_ovp_channel_2.setDecimals(3)
        self.doubleSpinBox_ovp_channel_2.setMaximum(30.0)
        self.doubleSpinBox_ovp_channel_2.setSingleStep(1.0)
        self.doubleSpinBox_ovp_channel_2.setObjectName("doubleSpinBox_ovp_channel_2")
        self.gridLayout_channel_2.addWidget(self.doubleSpinBox_ovp_channel_2, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_channel_2.addItem(spacerItem2, 2, 3, 1, 1)
        self.label_ovp_channel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ovp_channel_2.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_ovp_channel_2.setObjectName("label_ovp_channel_2")
        self.gridLayout_channel_2.addWidget(self.label_ovp_channel_2, 4, 0, 1, 1)
        self.label_ocp_channel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ocp_channel_2.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_ocp_channel_2.setObjectName("label_ocp_channel_2")
        self.gridLayout_channel_2.addWidget(self.label_ocp_channel_2, 5, 0, 1, 1)
        self.doubleSpinBox_ocp_channel_2 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_ocp_channel_2.setFont(font)
        self.doubleSpinBox_ocp_channel_2.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_ocp_channel_2.setDecimals(3)
        self.doubleSpinBox_ocp_channel_2.setMaximum(3.0)
        self.doubleSpinBox_ocp_channel_2.setSingleStep(0.1)
        self.doubleSpinBox_ocp_channel_2.setObjectName("doubleSpinBox_ocp_channel_2")
        self.gridLayout_channel_2.addWidget(self.doubleSpinBox_ocp_channel_2, 5, 1, 1, 1)
        self.doubleSpinBox_current_channel_2 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_current_channel_2.setFont(font)
        self.doubleSpinBox_current_channel_2.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_current_channel_2.setDecimals(3)
        self.doubleSpinBox_current_channel_2.setMaximum(3.0)
        self.doubleSpinBox_current_channel_2.setSingleStep(0.1)
        self.doubleSpinBox_current_channel_2.setObjectName("doubleSpinBox_current_channel_2")
        self.gridLayout_channel_2.addWidget(self.doubleSpinBox_current_channel_2, 3, 1, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_voltage_measured_values_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_voltage_measured_values_2.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_voltage_measured_values_2.setObjectName("pushButton_voltage_measured_values_2")
        self.horizontalLayout_3.addWidget(self.pushButton_voltage_measured_values_2)
        self.pushButton_current_measured_values_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_current_measured_values_2.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_current_measured_values_2.setObjectName("pushButton_current_measured_values_2")
        self.horizontalLayout_3.addWidget(self.pushButton_current_measured_values_2)
        self.pushButton_power_measured_values_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_power_measured_values_2.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_power_measured_values_2.setObjectName("pushButton_power_measured_values_2")
        self.horizontalLayout_3.addWidget(self.pushButton_power_measured_values_2)
        self.gridLayout_channel_2.addLayout(self.horizontalLayout_3, 7, 0, 1, 4)
        self.doubleSpinBox_voltage_channel_2 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_voltage_channel_2.setFont(font)
        self.doubleSpinBox_voltage_channel_2.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_voltage_channel_2.setDecimals(3)
        self.doubleSpinBox_voltage_channel_2.setMaximum(30.0)
        self.doubleSpinBox_voltage_channel_2.setSingleStep(1.0)
        self.doubleSpinBox_voltage_channel_2.setObjectName("doubleSpinBox_voltage_channel_2")
        self.gridLayout_channel_2.addWidget(self.doubleSpinBox_voltage_channel_2, 2, 1, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_cvcc_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_cvcc_2.setMinimumSize(QtCore.QSize(30, 0))
        self.label_cvcc_2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_cvcc_2.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_cvcc_2.setObjectName("label_cvcc_2")
        self.horizontalLayout_6.addWidget(self.label_cvcc_2)
        self.led_cvcc_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_cvcc_2.sizePolicy().hasHeightForWidth())
        self.led_cvcc_2.setSizePolicy(sizePolicy)
        self.led_cvcc_2.setMinimumSize(QtCore.QSize(25, 25))
        self.led_cvcc_2.setMaximumSize(QtCore.QSize(25, 25))
        self.led_cvcc_2.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(0, 255, 127)")
        self.led_cvcc_2.setText("")
        self.led_cvcc_2.setPixmap(QtGui.QPixmap("../../../Desktop/leb_disabled - Copy.png"))
        self.led_cvcc_2.setScaledContents(True)
        self.led_cvcc_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.led_cvcc_2.setObjectName("led_cvcc_2")
        self.horizontalLayout_6.addWidget(self.led_cvcc_2)
        self.gridLayout_channel_2.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_channel_2)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.gridLayout_channel_3 = QtWidgets.QGridLayout()
        self.gridLayout_channel_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_channel_3.setObjectName("gridLayout_channel_3")
        self.pushButton_ovp_channel_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ovp_channel_3.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_ovp_channel_3.setFont(font)
        self.pushButton_ovp_channel_3.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.pushButton_ovp_channel_3.setObjectName("pushButton_ovp_channel_3")
        self.gridLayout_channel_3.addWidget(self.pushButton_ovp_channel_3, 4, 2, 1, 1)
        self.label_channel_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_channel_3.setFont(font)
        self.label_channel_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_channel_3.setStyleSheet("font: 75 14pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_channel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_channel_3.setObjectName("label_channel_3")
        self.gridLayout_channel_3.addWidget(self.label_channel_3, 1, 1, 1, 2)
        self.pushButton_enable_channel_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_enable_channel_3.sizePolicy().hasHeightForWidth())
        self.pushButton_enable_channel_3.setSizePolicy(sizePolicy)
        self.pushButton_enable_channel_3.setMinimumSize(QtCore.QSize(130, 45))
        self.pushButton_enable_channel_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_enable_channel_3.setFont(font)
        self.pushButton_enable_channel_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_enable_channel_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_enable_channel_3.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 10px;\n"
"font: 75 11pt \"Trebuchet MS\";")
        self.pushButton_enable_channel_3.setObjectName("pushButton_enable_channel_3")
        self.gridLayout_channel_3.addWidget(self.pushButton_enable_channel_3, 6, 1, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_ovp_channel_3 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_ovp_channel_3.setFont(font)
        self.doubleSpinBox_ovp_channel_3.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_ovp_channel_3.setDecimals(3)
        self.doubleSpinBox_ovp_channel_3.setMaximum(30.0)
        self.doubleSpinBox_ovp_channel_3.setSingleStep(1.0)
        self.doubleSpinBox_ovp_channel_3.setObjectName("doubleSpinBox_ovp_channel_3")
        self.gridLayout_channel_3.addWidget(self.doubleSpinBox_ovp_channel_3, 4, 1, 1, 1)
        self.pushButton_ocp_channel_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_ocp_channel_3.setMinimumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_ocp_channel_3.setFont(font)
        self.pushButton_ocp_channel_3.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: #1f1d2c;\n"
"border-radius: 10px;\n"
"padding: 5px;")
        self.pushButton_ocp_channel_3.setObjectName("pushButton_ocp_channel_3")
        self.gridLayout_channel_3.addWidget(self.pushButton_ocp_channel_3, 5, 2, 1, 1)
        self.label_current_channel_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_current_channel_3.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_current_channel_3.setObjectName("label_current_channel_3")
        self.gridLayout_channel_3.addWidget(self.label_current_channel_3, 3, 0, 1, 1)
        self.label_voltage_channel_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_voltage_channel_3.setFont(font)
        self.label_voltage_channel_3.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_voltage_channel_3.setObjectName("label_voltage_channel_3")
        self.gridLayout_channel_3.addWidget(self.label_voltage_channel_3, 2, 0, 1, 1)
        self.label_ocp_channel_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ocp_channel_3.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_ocp_channel_3.setObjectName("label_ocp_channel_3")
        self.gridLayout_channel_3.addWidget(self.label_ocp_channel_3, 5, 0, 1, 1)
        self.label_ovp_channel_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_ovp_channel_3.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_ovp_channel_3.setObjectName("label_ovp_channel_3")
        self.gridLayout_channel_3.addWidget(self.label_ovp_channel_3, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_channel_3.addItem(spacerItem3, 2, 3, 1, 1)
        self.doubleSpinBox_ocp_channel_3 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_ocp_channel_3.setFont(font)
        self.doubleSpinBox_ocp_channel_3.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_ocp_channel_3.setDecimals(3)
        self.doubleSpinBox_ocp_channel_3.setMaximum(3.0)
        self.doubleSpinBox_ocp_channel_3.setSingleStep(0.1)
        self.doubleSpinBox_ocp_channel_3.setObjectName("doubleSpinBox_ocp_channel_3")
        self.gridLayout_channel_3.addWidget(self.doubleSpinBox_ocp_channel_3, 5, 1, 1, 1)
        self.doubleSpinBox_voltage_channel_3 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_voltage_channel_3.setFont(font)
        self.doubleSpinBox_voltage_channel_3.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_voltage_channel_3.setDecimals(3)
        self.doubleSpinBox_voltage_channel_3.setMaximum(5.0)
        self.doubleSpinBox_voltage_channel_3.setSingleStep(1.0)
        self.doubleSpinBox_voltage_channel_3.setObjectName("doubleSpinBox_voltage_channel_3")
        self.gridLayout_channel_3.addWidget(self.doubleSpinBox_voltage_channel_3, 2, 1, 1, 2)
        self.doubleSpinBox_current_channel_3 = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.doubleSpinBox_current_channel_3.setFont(font)
        self.doubleSpinBox_current_channel_3.setStyleSheet("QDoubleSpinBox\n"
"{\n"
"border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;\n"
"}")
        self.doubleSpinBox_current_channel_3.setDecimals(3)
        self.doubleSpinBox_current_channel_3.setMaximum(3.0)
        self.doubleSpinBox_current_channel_3.setSingleStep(0.1)
        self.doubleSpinBox_current_channel_3.setObjectName("doubleSpinBox_current_channel_3")
        self.gridLayout_channel_3.addWidget(self.doubleSpinBox_current_channel_3, 3, 1, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_voltage_measured_values_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_voltage_measured_values_3.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_voltage_measured_values_3.setObjectName("pushButton_voltage_measured_values_3")
        self.horizontalLayout_4.addWidget(self.pushButton_voltage_measured_values_3)
        self.pushButton_current_measured_values_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_current_measured_values_3.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_current_measured_values_3.setObjectName("pushButton_current_measured_values_3")
        self.horizontalLayout_4.addWidget(self.pushButton_current_measured_values_3)
        self.pushButton_power_measured_values_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_power_measured_values_3.setStyleSheet("border : 3px solid #1f1d2c;\n"
"color: rgb(250, 250, 250);\n"
"background-color: #262837;\n"
"border-radius: 5px;\n"
"padding: 1px;")
        self.pushButton_power_measured_values_3.setObjectName("pushButton_power_measured_values_3")
        self.horizontalLayout_4.addWidget(self.pushButton_power_measured_values_3)
        self.gridLayout_channel_3.addLayout(self.horizontalLayout_4, 7, 0, 1, 4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_cvcc_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_cvcc_3.setMinimumSize(QtCore.QSize(30, 0))
        self.label_cvcc_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_cvcc_3.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(243, 243, 243);")
        self.label_cvcc_3.setObjectName("label_cvcc_3")
        self.horizontalLayout_7.addWidget(self.label_cvcc_3)
        self.led_cvcc_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_cvcc_3.sizePolicy().hasHeightForWidth())
        self.led_cvcc_3.setSizePolicy(sizePolicy)
        self.led_cvcc_3.setMinimumSize(QtCore.QSize(25, 25))
        self.led_cvcc_3.setMaximumSize(QtCore.QSize(25, 25))
        self.led_cvcc_3.setStyleSheet("font: 75 11pt \"Trebuchet MS\";\n"
"color: rgb(0, 255, 127)")
        self.led_cvcc_3.setText("")
        self.led_cvcc_3.setPixmap(QtGui.QPixmap("../../../Desktop/leb_disabled - Copy.png"))
        self.led_cvcc_3.setScaledContents(True)
        self.led_cvcc_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.led_cvcc_3.setObjectName("led_cvcc_3")
        self.horizontalLayout_7.addWidget(self.led_cvcc_3)
        self.gridLayout_channel_3.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_channel_3)
        self.graphicsView = PlotWidget(self.tab_RigolDp832)
        self.graphicsView.setGeometry(QtCore.QRect(30, 300, 951, 301))
        self.graphicsView.setStyleSheet("color: rgb(239, 239, 239);")
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tab_RigolDp832, "")
        self.tab_Keithley2308 = QtWidgets.QWidget()
        self.tab_Keithley2308.setEnabled(True)
        self.tab_Keithley2308.setAutoFillBackground(False)
        self.tab_Keithley2308.setStyleSheet("background-color: #2e303f;")
        self.tab_Keithley2308.setObjectName("tab_Keithley2308")
        self.tabWidget.addTab(self.tab_Keithley2308, "")
        self.tab_ItechIT = QtWidgets.QWidget()
        self.tab_ItechIT.setEnabled(False)
        self.tab_ItechIT.setStyleSheet("background-color: #2e303f;")
        self.tab_ItechIT.setObjectName("tab_ItechIT")
        self.tabWidget.addTab(self.tab_ItechIT, "")
        self.tab_RigolDS1054 = QtWidgets.QWidget()
        self.tab_RigolDS1054.setEnabled(False)
        self.tab_RigolDS1054.setStyleSheet("background-color: #2e303f;")
        self.tab_RigolDS1054.setObjectName("tab_RigolDS1054")
        self.tabWidget.addTab(self.tab_RigolDS1054, "")
        self.tab_Multimeter = QtWidgets.QWidget()
        self.tab_Multimeter.setEnabled(False)
        self.tab_Multimeter.setStyleSheet("background-color: #2e303f;")
        self.tab_Multimeter.setObjectName("tab_Multimeter")
        self.tabWidget.addTab(self.tab_Multimeter, "")
        self.tab_Siglent = QtWidgets.QWidget()
        self.tab_Siglent.setEnabled(False)
        self.tab_Siglent.setStyleSheet("background-color: #2e303f;")
        self.tab_Siglent.setObjectName("tab_Siglent")
        self.tabWidget.addTab(self.tab_Siglent, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 32))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("QMenuBar::item {\n"
"padding: 10px;\n"
"padding-bottom: 5px;\n"
"padding-top: 5px;\n"
"border-bottom: 1px solid #1f1d2c;\n"
"background-color: #262837;\n"
"border-bottom-right-radius: 10px 10px;\n"
"border-bottom-left-radius: 10px 10px;\n"
"}\n"
":enabled {color: rgb(235, 235, 235);\n"
"                selection-background-color: #181721;}\n"
":disabled {color: rgb(105, 105, 105);\n"
"                selection-background-color: #181721;}")
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setStyleSheet("background-color: #262837;")
        self.menuSettings.setObjectName("menuSettings")
        self.menuChoose_lab_equipment = QtWidgets.QMenu(self.menuSettings)
        self.menuChoose_lab_equipment.setObjectName("menuChoose_lab_equipment")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("background-color: #262837;")
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_Controller_Repository = QtWidgets.QAction(MainWindow)
        self.actionOpen_Controller_Repository.setObjectName("actionOpen_Controller_Repository")
        self.settings_check_Rigol_DP832 = QtWidgets.QAction(MainWindow)
        self.settings_check_Rigol_DP832.setCheckable(True)
        self.settings_check_Rigol_DP832.setChecked(False)
        self.settings_check_Rigol_DP832.setObjectName("settings_check_Rigol_DP832")
        self.settings_check_Keithley_2308 = QtWidgets.QAction(MainWindow)
        self.settings_check_Keithley_2308.setCheckable(True)
        self.settings_check_Keithley_2308.setChecked(False)
        self.settings_check_Keithley_2308.setObjectName("settings_check_Keithley_2308")
        self.settings_check_Itech_IT8512 = QtWidgets.QAction(MainWindow)
        self.settings_check_Itech_IT8512.setCheckable(True)
        self.settings_check_Itech_IT8512.setEnabled(False)
        self.settings_check_Itech_IT8512.setVisible(True)
        self.settings_check_Itech_IT8512.setObjectName("settings_check_Itech_IT8512")
        self.settings_check_Rigol_DS1054 = QtWidgets.QAction(MainWindow)
        self.settings_check_Rigol_DS1054.setCheckable(True)
        self.settings_check_Rigol_DS1054.setEnabled(False)
        self.settings_check_Rigol_DS1054.setObjectName("settings_check_Rigol_DS1054")
        self.settings_check_Multimeter_34401A = QtWidgets.QAction(MainWindow)
        self.settings_check_Multimeter_34401A.setCheckable(True)
        self.settings_check_Multimeter_34401A.setEnabled(False)
        self.settings_check_Multimeter_34401A.setObjectName("settings_check_Multimeter_34401A")
        self.settings_check_Siglent_SDG2122X = QtWidgets.QAction(MainWindow)
        self.settings_check_Siglent_SDG2122X.setCheckable(True)
        self.settings_check_Siglent_SDG2122X.setEnabled(False)
        self.settings_check_Siglent_SDG2122X.setObjectName("settings_check_Siglent_SDG2122X")
        self.actionOpen_Drivers_Repository = QtWidgets.QAction(MainWindow)
        self.actionOpen_Drivers_Repository.setObjectName("actionOpen_Drivers_Repository")
        self.menuChoose_lab_equipment.addAction(self.settings_check_Rigol_DP832)
        self.menuChoose_lab_equipment.addAction(self.settings_check_Keithley_2308)
        self.menuChoose_lab_equipment.addAction(self.settings_check_Itech_IT8512)
        self.menuChoose_lab_equipment.addAction(self.settings_check_Rigol_DS1054)
        self.menuChoose_lab_equipment.addAction(self.settings_check_Multimeter_34401A)
        self.menuChoose_lab_equipment.addAction(self.settings_check_Siglent_SDG2122X)
        self.menuSettings.addAction(self.menuChoose_lab_equipment.menuAction())
        self.menuHelp.addAction(self.actionOpen_Controller_Repository)
        self.menuHelp.addAction(self.actionOpen_Drivers_Repository)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">ⓘ</span></p><p>Select Lab equipment <br/>from settings to start</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_starting_page), _translate("MainWindow", "Starting Page"))
        self.pushButton_ovp_channel_1.setText(_translate("MainWindow", "OFF"))
        self.label_channel_1.setText(_translate("MainWindow", "Channel 1"))
        self.pushButton_enable_channel_1.setText(_translate("MainWindow", "OFF"))
        self.doubleSpinBox_ovp_channel_1.setSuffix(_translate("MainWindow", " V"))
        self.pushButton_ocp_channel_1.setText(_translate("MainWindow", "OFF"))
        self.label_current_channel_1.setText(_translate("MainWindow", "Current"))
        self.label_voltage_channel_1.setText(_translate("MainWindow", "Voltage"))
        self.label_ocp_channel_1.setText(_translate("MainWindow", "OCP"))
        self.label_ovp_channel_1.setText(_translate("MainWindow", "OVP"))
        self.doubleSpinBox_ocp_channel_1.setSuffix(_translate("MainWindow", " A"))
        self.doubleSpinBox_voltage_channel_1.setSuffix(_translate("MainWindow", " V"))
        self.doubleSpinBox_current_channel_1.setSuffix(_translate("MainWindow", " A"))
        self.pushButton_voltage_measured_values_1.setText(_translate("MainWindow", "0.000 V"))
        self.pushButton_current_measured_values_1.setText(_translate("MainWindow", "0.000 A"))
        self.pushButton_power_measured_values_1.setText(_translate("MainWindow", "0.000 W"))
        self.label_cvcc_1.setText(_translate("MainWindow", "CV"))
        self.label_voltage_channel_2.setText(_translate("MainWindow", "Voltage"))
        self.pushButton_ovp_channel_2.setText(_translate("MainWindow", "OFF"))
        self.pushButton_enable_channel_2.setText(_translate("MainWindow", "OFF"))
        self.label_channel_2.setText(_translate("MainWindow", "Channel 2"))
        self.pushButton_ocp_channel_2.setText(_translate("MainWindow", "OFF"))
        self.label_current_channel_2.setText(_translate("MainWindow", "Current"))
        self.doubleSpinBox_ovp_channel_2.setSuffix(_translate("MainWindow", " V"))
        self.label_ovp_channel_2.setText(_translate("MainWindow", "OVP"))
        self.label_ocp_channel_2.setText(_translate("MainWindow", "OCP"))
        self.doubleSpinBox_ocp_channel_2.setSuffix(_translate("MainWindow", " A"))
        self.doubleSpinBox_current_channel_2.setSuffix(_translate("MainWindow", " A"))
        self.pushButton_voltage_measured_values_2.setText(_translate("MainWindow", "0.000 V"))
        self.pushButton_current_measured_values_2.setText(_translate("MainWindow", "0.000 A"))
        self.pushButton_power_measured_values_2.setText(_translate("MainWindow", "0.000 W"))
        self.doubleSpinBox_voltage_channel_2.setSuffix(_translate("MainWindow", " V"))
        self.label_cvcc_2.setText(_translate("MainWindow", "CV"))
        self.pushButton_ovp_channel_3.setText(_translate("MainWindow", "OFF"))
        self.label_channel_3.setText(_translate("MainWindow", "Channel 3"))
        self.pushButton_enable_channel_3.setText(_translate("MainWindow", "OFF"))
        self.doubleSpinBox_ovp_channel_3.setSuffix(_translate("MainWindow", " V"))
        self.pushButton_ocp_channel_3.setText(_translate("MainWindow", "OFF"))
        self.label_current_channel_3.setText(_translate("MainWindow", "Current"))
        self.label_voltage_channel_3.setText(_translate("MainWindow", "Voltage"))
        self.label_ocp_channel_3.setText(_translate("MainWindow", "OCP"))
        self.label_ovp_channel_3.setText(_translate("MainWindow", "OVP"))
        self.doubleSpinBox_ocp_channel_3.setSuffix(_translate("MainWindow", " A"))
        self.doubleSpinBox_voltage_channel_3.setSuffix(_translate("MainWindow", " V"))
        self.doubleSpinBox_current_channel_3.setSuffix(_translate("MainWindow", " A"))
        self.pushButton_voltage_measured_values_3.setText(_translate("MainWindow", "0.000 V"))
        self.pushButton_current_measured_values_3.setText(_translate("MainWindow", "0.000 A"))
        self.pushButton_power_measured_values_3.setText(_translate("MainWindow", "0.000 W"))
        self.label_cvcc_3.setText(_translate("MainWindow", "CV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_RigolDp832), _translate("MainWindow", "Rigol DP832"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Keithley2308), _translate("MainWindow", "Keithley 2308"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ItechIT), _translate("MainWindow", "Itech IT8512"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_RigolDS1054), _translate("MainWindow", "Rigol DS1054"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Multimeter), _translate("MainWindow", "Multimeter 34401A"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Siglent), _translate("MainWindow", "Siglent SDG2122X"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuChoose_lab_equipment.setTitle(_translate("MainWindow", "Choose lab equipment"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_Controller_Repository.setText(_translate("MainWindow", "Open Controller Repository"))
        self.settings_check_Rigol_DP832.setText(_translate("MainWindow", "Rigol DP832"))
        self.settings_check_Keithley_2308.setText(_translate("MainWindow", "Keithley 2308"))
        self.settings_check_Itech_IT8512.setText(_translate("MainWindow", "Itech IT8512"))
        self.settings_check_Rigol_DS1054.setText(_translate("MainWindow", "Rigol DS1054"))
        self.settings_check_Multimeter_34401A.setText(_translate("MainWindow", "Multimeter 34401A"))
        self.settings_check_Siglent_SDG2122X.setText(_translate("MainWindow", "Siglent SDG2122X"))
        self.actionOpen_Drivers_Repository.setText(_translate("MainWindow", "Open Drivers Repository"))
from pyqtgraph import PlotWidget
